<?php

return [
    'cache_version' => '1.7',
    'feature_flag' => 'reference_wave1',

    'canary' => [
        'enabled' => false,
        'company_ids' => [],
        'unscoped_reference_all' => true,
    ],

    'plan_status' => [
        'slim_reference_payload_complete' => true,
    ],

    'payload_budget_bytes' => [
        'warehouses_all' => 512_000,
        'cash_registers_all' => 512_000,
        'categories_all' => 512_000,
        'order_statuses_all' => 256_000,
        'project_statuses_all' => 256_000,
        'task_statuses_all' => 256_000,
        'transaction_categories_all' => 512_000,
        'roles_all' => 256_000,
        'leave_types_all' => 128_000,
        'order_status_categories_all' => 128_000,
        'warehouses_index' => 512_000,
        'cash_registers_index' => 512_000,
        'categories_index' => 512_000,
        'categories_parents' => 512_000,
        'order_statuses_index' => 256_000,
        'project_statuses_index' => 256_000,
        'task_statuses_index' => 256_000,
        'transaction_categories_index' => 512_000,
        'roles_index' => 256_000,
        'leave_types_index' => 128_000,
        'order_status_categories_index' => 128_000,
        'departments_all' => 256_000,
        'departments_index' => 256_000,
        'message_templates_all' => 512_000,
        'message_templates_index' => 512_000,
        'company_holidays_all' => 256_000,
        'company_holidays_index' => 256_000,
        'transaction_templates_all' => 512_000,
        'transaction_templates_index' => 512_000,
        'leaves_all' => 512_000,
        'leaves_index' => 512_000,
        'projects_all' => 1_048_576,
        'projects_index' => 1_048_576,
        'tasks_index' => 1_048_576,
        'products_search' => 1_048_576,
        'users_search' => 512_000,
        'clients_search' => 512_000,
    ],

    'reference_top_level_keys' => [
        'warehouses' => ['id', 'name', 'users'],
        'cash_registers' => ['balance', 'currency', 'currency_id', 'icon', 'id', 'is_cash', 'is_working_minus', 'name', 'users'],
        'categories' => ['creator', 'creator_id', 'id', 'name', 'parent_id', 'parent_name', 'users'],
        'order_statuses' => ['category', 'category_id', 'created_at', 'id', 'is_active', 'kanban_outcome', 'name', 'updated_at'],
        'project_statuses' => ['color', 'created_at', 'creator_id', 'id', 'is_visible', 'kanban_outcome', 'name', 'updated_at', 'user'],
        'task_statuses' => ['color', 'created_at', 'creator_id', 'id', 'kanban_outcome', 'name', 'updated_at', 'user'],
        'transaction_categories' => ['created_at', 'creator', 'creator_id', 'id', 'name', 'parent', 'parent_id', 'type', 'updated_at'],
        'roles' => ['company_id', 'created_at', 'id', 'name', 'updated_at'],
        'leave_types' => ['color', 'created_at', 'id', 'is_penalty', 'name', 'updated_at'],
        'order_status_categories' => ['color', 'created_at', 'creator_id', 'id', 'name', 'updated_at'],
        'departments' => [
            'company_id', 'created_at', 'deputy_head', 'deputy_head_id', 'description', 'head', 'head_id', 'id', 'parent_id', 'title', 'updated_at', 'users',
        ],
        'message_templates' => [
            'company', 'company_id', 'created_at', 'creator', 'creator_id', 'id', 'is_active', 'name', 'type', 'updated_at',
        ],
        'company_holidays' => ['color', 'company_id', 'created_at', 'date', 'end_date', 'id', 'is_recurring', 'name', 'updated_at'],
        'transaction_templates' => [
            'amount', 'cash_id', 'cash_register', 'category', 'category_id', 'client', 'client_id', 'created_at', 'creator', 'creator_id', 'currency', 'currency_id', 'icon', 'id', 'name', 'note', 'project', 'project_id', 'type', 'updated_at',
        ],
        'leaves' => [
            'comment', 'company_id', 'created_at', 'date_from', 'date_to', 'id', 'leave_type', 'leave_type_id', 'updated_at', 'user', 'user_id',
        ],
        'projects' => [
            'budget', 'client', 'client_id', 'created_at', 'creator', 'creator_id', 'currency', 'currency_id', 'date', 'description', 'files', 'id', 'name', 'status', 'status_id', 'updated_at', 'users',
        ],
        'tasks' => [
            'checklist', 'comments', 'complexity', 'complexity_icons', 'complexity_label', 'created_at', 'creator', 'deadline', 'description', 'executor', 'files', 'id', 'priority', 'priority_icons', 'priority_label', 'project', 'status', 'status_id', 'supervisor', 'title', 'updated_at',
        ],
    ],

    'reference_nested_keys' => [
        'order_statuses.category' => ['color', 'created_at', 'creator_id', 'id', 'name', 'updated_at'],
        'warehouses.users_item' => ['id', 'name', 'surname'],
        'cash_registers.users_item' => ['id', 'name'],
        'cash_registers.currency' => ['id', 'name', 'symbol'],
        'categories.users_item' => ['id', 'name', 'surname'],
        'categories.creator' => ['id', 'name'],
        'transaction_categories.parent' => ['id', 'name'],
        'transaction_categories.creator' => ['id', 'name'],
        'project_statuses.user' => ['id', 'name', 'surname'],
        'task_statuses.user' => ['id', 'name', 'surname'],
        'departments.users_item' => ['id', 'name', 'surname'],
        'departments.head' => ['id', 'name', 'surname'],
        'departments.deputy_head' => ['id', 'name', 'surname'],
        'message_templates.creator' => ['id', 'name', 'surname'],
        'message_templates.company' => ['id', 'name'],
        'transaction_templates.cash_register' => ['company_id', 'currency_id', 'id', 'is_cash', 'name'],
        'transaction_templates.category' => ['id', 'name', 'type'],
        'transaction_templates.client' => [
            'balance', 'client_type', 'created_at', 'emails', 'first_name', 'id', 'is_conflict', 'is_supplier', 'last_name', 'patronymic', 'phones', 'position', 'updated_at',
        ],
        'transaction_templates.creator' => ['id', 'name', 'surname'],
        'transaction_templates.currency' => ['id', 'name', 'symbol'],
        'transaction_templates.project' => ['id', 'name'],
        'leaves.leave_type' => ['color', 'created_at', 'id', 'is_penalty', 'name', 'updated_at'],
        'leaves.user' => ['email', 'id', 'name', 'surname'],
        'projects.client' => [
            'balance', 'client_type', 'created_at', 'emails', 'first_name', 'id', 'is_conflict', 'is_supplier', 'last_name', 'patronymic', 'phones', 'position', 'updated_at',
        ],
        'projects.creator' => ['id', 'name', 'photo'],
        'projects.currency' => ['id', 'is_default', 'is_report', 'name', 'status', 'symbol'],
        'projects.status' => ['color', 'id', 'is_visible', 'name'],
        'projects.users_item' => ['id', 'name'],
        'tasks.creator' => ['email', 'id', 'name'],
        'tasks.executor' => ['email', 'id', 'name', 'photo', 'position', 'surname'],
        'tasks.project' => ['id', 'name'],
        'tasks.status' => ['color', 'id', 'name'],
        'tasks.supervisor' => ['email', 'id', 'name', 'photo', 'position', 'surname'],
    ],

    'search_item_top_level_keys' => [
        'products' => [
            'barcode', 'categories', 'category_id', 'category_name', 'description', 'id', 'image', 'name',
            'purchase_price', 'retail_price', 'sku', 'stock_quantity', 'type', 'unit_id', 'unit_name', 'unit_short_name',
            'wholesale_price',
        ],
        'users' => ['email', 'id', 'is_active', 'name', 'photo', 'position', 'surname'],
        'clients' => ['balance', 'client_type', 'first_name', 'id', 'is_conflict', 'is_supplier', 'last_name', 'position', 'primary_phone'],
    ],
];
